export default {
  ACTION_MENU_TOGGLE: 'ACTION_MENU_TOGGLE',
  SELECT_ALL_TOGGLE: 'SELECT_ALL_TOGGLE',
  MULTIPLE_RECORDS_TOGGLE: 'MULTIPLE_RECORDS_TOGGLE',
  ROW_SELECT: 'ROW_SELECT',
  ROW_LIST_SELECT: 'ROW_LIST_SELECT',
  DRAGGED_ROW_SET: 'DRAGGED_ROW_SET',
  DRAGGING_TOGGLE: 'DRAGGING_TOGGLE',
};
