version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium-jessie
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn build
  test:
    docker:
      - image: circleci/node:dubnium-jessie
    steps:
      - checkout
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
